steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: Install
    args:
      - 'install'
      - '-P${_PROFILE}'
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/airplane-backend:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/airplane-backend:$SHORT_SHA'
