INSERT INTO `oauth_client_details`
(
    `client_id`,
    `resource_ids`,
    `client_secret`,
    `scope`,
    `authorized_grant_types`,
    `web_server_redirect_uri`,
    `authorities`,
    `access_token_validity`,
    `refresh_token_validity`,
    `additional_information`,
    `autoapprove`
 )
VALUES
(
    'clientId',
    '',
    '$2a$10$1PgZzvyCUxXPj6mXrMdKvuFhTzYdEusc7WiGEEmtCPTpqkBK4XJZW',
    'read,write',
    'password,refresh_token',
    '',
    '',
    '1800',
    '604800',
    '{}',
    ''
 );
